### PR TITLE
Ensure GO_SOURCE_RELATIVE option is picked up by gateway plugin

### PR DESCRIPTION
**Pull request by vaijab**

### CODE REVIEW

**Comment by vaijab** [comment]
@ido-namely pinging you as suggested in the contributing section.

**Comment by ido-namely** [comment]
> @ido-namely pinging you as suggested in the contributing section.

Hi @vaijab , I apologize for the delay, I have a bit of a backlog but I will try to get to this PR as soon as I can.

**Comment by vaijab** [comment]
@ido-namely just a friendly reminder. :-)

**Comment by ido-namely** [comment]
> @ido-namely just a friendly reminder. :-)

Hi @vaijab , again, apologies for the delay.

Would you mind adding tests to your change? should be easy to check that with the flag set, the expected file is created in the expected path. Take a look at https://github.com/namely/docker-protoc/blob/master/all/test.sh.

**Comment by owenthereal** [comment]
:wave: Any update on this PR?

**Comment by ido-namely** [comment]
> 👋 Any update on this PR?

Hi @owenthereal,
Thanks for your interest.
We are unfortunately busy at the moment to take care of this PR but you should feel free to take over and add the test that would allow us to merge this PR, if you have the time.

**Comment by ido-namely** [comment]
superseded by https://github.com/namely/docker-protoc/pull/327

**Pull request closed without merging**
