### PR TITLE
Add arg "--scala_opt" to support scalapbc options

### PR DESCRIPTION
**Pull request by mwgrimm**
As described in https://scalapb.github.io/scalapbc.html, scalapbc options are included in the `--scala_out` argument and provided as a comma-separated list followed by a ":" and the output directory.

Ex.
`bin/scalapbc my.proto --scala_out=OPT1,OPT2:path/to/output/dir/`

### CODE REVIEW

**Comment by spoonscen** [comment]
Hey @aldelucca1 Looks like I missed this when I added the scala support. We would love a review when you get a chance.

Thanks

**Comment by spoonscen** [comment]
@ido-namely Hey folks! We would love to get this moved forward.

**Comment by ido-namely** [comment]
> @ido-namely Hey folks! We would love to get this moved forward.

Hi @spoonscen , sorry for the delay and thank you for the contribution.
This looks good to me. However, would you mind incrementing the version to 2 [here](https://github.com/namely/docker-protoc/blob/master/variables.sh#L7)?

**Comment by mwgrimm** [comment]
> > @ido-namely Hey folks! We would love to get this moved forward.
> 
> Hi @spoonscen , sorry for the delay and thank you for the contribution.
> This looks good to me. However, would you mind incrementing the version to 2 [here](https://github.com/namely/docker-protoc/blob/master/variables.sh#L7)?

Done!

**Pull request merged**
