### PR TITLE
feat: update grpc-web to 1.3.0

### LINKED ISSUE #276: Update grpc-web to 1.3.0

### PR DESCRIPTION
**Pull request by trietsch**
Fixes #276

### CODE REVIEW

**Comment by trietsch** [comment]
We've confirmed that this image is working for our `grpc-web` based application.

**Review by ido-namely — APPROVED** [review]

**Comment by ido-namely** [comment]
Thanks for the contribution @trietsch 

I ran the tests locally with this image and they passed. This is good to merge as far as I'm concerned (we'll wait for another approver)

**Comment by trietsch** [comment]
@ido-namely thanks for the review! In the meantime, we're using this image already, which we built ourselves. 
Keep up the good work with this image, it's very very useful! 😁

**Comment by trietsch** [comment]
By the way, you could use [Renovate Bot](https://docs.renovatebot.com/) to automatically create PRs like this, with the [custom regex manager](https://docs.renovatebot.com/modules/manager/regex/).

**Review by abe545 — APPROVED** [review]

**Comment by ido-namely** [comment]
> @ido-namely By the way, you could use [Renovate Bot](https://docs.renovatebot.com/) to automatically create PRs like this, with the [custom regex manager](https://docs.renovatebot.com/modules/manager/regex/).

Thanks @trietsch , looks interesting, I was only familiar with dependabot. 
Meantime `1.42_1` is on the way

**Comment by trietsch** [comment]
@ido-namely great. Good to hear :)
If you'd like, I could create a small config for Renovate which you could use. I'm currently only using Renovate on Gitlab, but they offer a hosted GitHub app, which can execute the configuration at a certain schedule for you. 

Let me know if you're interested, then I can help out.

**Comment by ido-namely** [comment]
> Renovate

Our team can discuss it, a config file can certainly help, thank you for offering.

**Pull request merged**
