### PR TITLE
Add js-out and grpc-web-out options

### LINKED ISSUE #71: Ability to customize node "import styles"
We would like to be able to customize the `js_out` portion of this `GEN_STRING`:

https://github.com/namely/docker-protoc/blob/3a872063daabf159aaed36a38d8467e2d00a1913/all/entrypoint.sh#L165-L167

Any thoughts on how you'd like to see that implemented?

### PR DESCRIPTION
**Pull request by artificial-aidan**
Add options to allow modifying the output options for node and web code
generation. Add web generation tests.

closes #71

### CODE REVIEW

**Comment by artificial-aidan** [comment]
closes #71

**Comment by artificial-aidan** [comment]
@ido-namely is this a reasonable contribution? It's necessary for our use case and hopefully could help others.

**Comment by artificial-aidan** [comment]
@ido-namely, or any other namely developers. What are the chances of getting this merged?

**Comment by nkushpir** [comment]
Hey @artificial-aidan, thanks for putting the PR! It looks good to me, please resolve the conflicts and bump build version in variables.sh https://github.com/namely/docker-protoc/blob/78ef0905e15f1fae2c4fd7e63320174bfaad92c7/variables.sh#L9

**Comment by artificial-aidan** [comment]
> Hey @artificial-aidan, thanks for putting the PR! It looks good to me, please resolve the conflicts and bump build version in variables.sh
> 
> https://github.com/namely/docker-protoc/blob/78ef0905e15f1fae2c4fd7e63320174bfaad92c7/variables.sh#L9

Done. Thanks!

**Review by nkushpir — APPROVED** [review]

**Review by ido-namely — APPROVED** [review]

**Pull request merged**
