### PR TITLE
add option for making go paths source_relative

### PR DESCRIPTION
**Pull request by jonathanburns**
I have a use case for the "source-relative" --go-out option. I'd like to add support for this option.

### CODE REVIEW

**Comment by jonathanburns** [comment]
@bobbytables @mdkess what are your thoughts on this?

**Comment by mdkess** [comment]
Looks good, I'll test and merge. Thanks for the contribution!

**Comment by jonathanburns** [comment]
@mdkess any update on this?

**Comment by bobbytables** [comment]
> @mdkess any update on this?

@jonathanburns - I'll take a look right now.

**Comment by bobbytables** [comment]
I tested this, the flag is appended and is backwards compatible.

**Comment by bobbytables** [comment]
@jonathanburns just pushed 1.14 with this change in it. Let me know if you're set :)

**Pull request merged**
