### PR TITLE
Remove maxdepth policy for Go

### PR DESCRIPTION
**Pull request by mehran-prs**
Can you see PR  #61  please? 
I removed maxdepth that is `1` for Golang.

### CODE REVIEW

**Comment by toyota790** [comment]
Can anyone help to review this PR? Or @mhamrah could you please review this? Thank you so much.

**Comment by mhamrah** [comment]
I'm not a member of this project anymore. I created grpckit as a (imo)
better replacement and suggest you use that for declarative generation and
plugin extensability:
https://medium.com/@mhamrah/introducing-grpckit-and-omniproto-a-toolchain-for-your-grpc-needs-9a92bd358bf1

**Comment by arturgspb** [comment]
https://github.com/namely/docker-protoc/issues/61#issuecomment-709618573

**Comment by ido-namely** [comment]
Hi @toyota790, unless you've decided to move to grpckit (Hi @mhamrah :)),
and you are still interested in contributing, would you mind adding a test case for this change?
Thanks and apologies for the late response.

**Comment by ido-namely** [comment]
BTW looks like this should be safe to do thanks to https://github.com/golang/protobuf/issues/39#issuecomment-593771984

**Comment by ido-namely** [comment]
superseded by https://github.com/namely/docker-protoc/pull/296

**Pull request closed without merging**
