### PR TITLE
fix(grpc_tools_node_ts_version): Bumping to 5.3.2

### PR DESCRIPTION
**Pull request by masterkidan**
This is to addres #259

### CODE REVIEW

**Comment by zaquestion** [comment]
@ido-namely this seem reasonable to you?

**Comment by ido-namely** [comment]
Hi @masterkidan , thanks for the contribution and apologies for the major delay.
Any chance you'll be willing to add a test, specifically for the oneof issue which I understand was your main concern?

**Comment by masterkidan** [comment]
Thanks @ido-namely , I am not sure how to add a test here as the bug is not in the code in the docker container ... the underlying tool that is used did add tests for this particular case, can you point an example of how one would add a test here ?

**Comment by ido-namely** [comment]
> Thanks @ido-namely , I am not sure how to add a test here as the bug is not in the code in the docker container ... the underlying tool that is used did add tests for this particular case, can you point an example of how one would add a test here ?

Hi @masterkidan , sure.
So our tests are mostly in this file https://github.com/namely/docker-protoc/blob/master/all/test.sh and the pattern is to call the image using the flags that you are testing/will generate the relevant file.
So you can add a oneof field to the test proto and then once the generated file is created, you can verify that the oneof field was generated as expected.
Feel free to reach out if you need further assistance.

**Comment by ido-namely** [comment]
superseded by https://github.com/namely/docker-protoc/pull/301

**Pull request closed without merging**
